<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WireMock.Net" Version="1.6.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShortP2P.Bot\ShortP2P.Bot.csproj" />
  </ItemGroup>

</Project>
